version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www/html:cached
  php:
    user: 1000:www-data
    image: dvlpm/php7.4-dev:latest
    volumes:
      - ./:/var/www/html
      - ./volumes/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      XDEBUG_CONFIG: remote_host=192.168.99.1