version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ./:/var/www/html:cached
            - composer:/var/www/.composer
    php:
        image: dvlpm/php7.4-dev:latest
        volumes:
            - ./:/var/www/html
            - ./volumes/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            XDEBUG_CONFIG: remote_host=${DEBUG_REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${DEBUG_SERVER_NAME}

    postgres:
        image: postgres:12-alpine
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
volumes:
    pgdata:
    composer:
