version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www/html:cached
  php:
    image: php:7.4-fpm
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html:cached
  mysql:
    image: mysql:8
    container_name: ${APP_NAME}_mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
